import type { QuizData } from '../../types';

export const fallbackQuizzes: QuizData[] = [
  {
    id: 'q1',
    question: 'Klepon adalah jajanan tradisional yang berasal dari pulau?',
    options: ['Jawa', 'Sumatra', 'Kalimantan', 'Sulawesi'],
    correctAnswerIndex: 0,
    explanation: 'Klepon adalah kue tradisional yang sangat populer di Pulau Jawa.',
  },
  {
    id: 'q2',
    question: 'Apa isian khas yang ada di dalam klepon?',
    options: ['Cokelat', 'Keju', 'Gula Merah', 'Selai Kacang'],
    correctAnswerIndex: 2,
    explanation: 'Klepon berisi gula merah cair yang meleleh saat digigit.',
  },
  {
    id: 'q3',
    question: 'Bahan utama pembuat kue putu adalah?',
    options: ['Tepung terigu', 'Tepung beras', 'Tepung tapioka', 'Tepung maizena'],
    correctAnswerIndex: 1,
    explanation: 'Kue putu dibuat dari tepung beras yang dikukus dalam bambu.',
  },
  {
    id: 'q4',
    question: 'Onde-onde dilapisi dengan bahan apa di bagian luarnya?',
    options: ['Kelapa parut', 'Wijen', 'Gula halus', 'Tepung panir'],
    correctAnswerIndex: 1,
    explanation: 'Onde-onde khas dilapisi biji wijen yang memberikan tekstur renyah.',
  },
  {
    id: 'q5',
    question: 'Lemper dibungkus menggunakan daun apa?',
    options: ['Daun mangga', 'Daun pisang', 'Daun pandan', 'Daun jati'],
    correctAnswerIndex: 1,
    explanation: 'Lemper dibungkus dengan daun pisang yang memberi aroma khas.',
  },
  {
    id: 'q6',
    question: 'Getuk terbuat dari bahan dasar apa?',
    options: ['Singkong', 'Kentang', 'Ubi jalar', 'Talas'],
    correctAnswerIndex: 0,
    explanation: 'Getuk dibuat dari singkong yang dikukus lalu ditumbuk halus.',
  },
  {
    id: 'q7',
    question: 'Serabi adalah kue tradisional yang cara memasaknya dengan?',
    options: ['Digoreng', 'Dipanggang di atas tungku', 'Direbus', 'Dikukus'],
    correctAnswerIndex: 1,
    explanation: 'Serabi dimasak di atas tungku kecil dengan cetakan tanah liat.',
  },
  {
    id: 'q8',
    question: 'Kue lapis terkenal karena ciri khasnya yang memiliki?',
    options: ['Rasa pedas', 'Banyak lapisan warna-warni', 'Bentuk segitiga', 'Isian daging'],
    correctAnswerIndex: 1,
    explanation: 'Kue lapis memiliki banyak lapisan tipis berwarna-warni yang indah.',
  },
  {
    id: 'q9',
    question: 'Risoles adalah jajanan yang berasal dari pengaruh kuliner negara?',
    options: ['Jepang', 'India', 'Belanda', 'Tiongkok'],
    correctAnswerIndex: 2,
    explanation: 'Risoles mendapat pengaruh dari kuliner Belanda pada masa kolonial.',
  },
  {
    id: 'q10',
    question: 'Warna hijau pada klepon biasanya berasal dari?',
    options: ['Pewarna buatan', 'Daun pandan', 'Daun suji', 'Daun pandan dan suji'],
    correctAnswerIndex: 3,
    explanation: 'Warna hijau klepon berasal dari campuran air daun pandan dan daun suji.',
  },
  {
    id: 'q11',
    question: 'Alat tradisional yang digunakan untuk memasak kue putu adalah?',
    options: ['Wajan', 'Bambu', 'Kukusan besar', 'Oven tanah'],
    correctAnswerIndex: 1,
    explanation: 'Kue putu dikukus di dalam potongan bambu yang menghasilkan suara khas.',
  },
  {
    id: 'q12',
    question: 'Apa nama bahan lengket yang menjadi dasar lemper?',
    options: ['Nasi putih', 'Ketan', 'Lontong', 'Nasi jagung'],
    correctAnswerIndex: 1,
    explanation: 'Lemper dibuat dari beras ketan yang dimasak dengan santan.',
  },
  {
    id: 'q13',
    question: 'Serabi Solo biasanya disajikan dengan kuah apa?',
    options: ['Kuah kari', 'Kuah santan gula merah', 'Kuah kecap', 'Kuah asam'],
    correctAnswerIndex: 1,
    explanation: 'Serabi khas Solo disajikan dengan kuah santan dan gula merah yang manis.',
  },
  {
    id: 'q14',
    question: 'Di Indonesia, jajanan pasar biasanya dijual di?',
    options: ['Supermarket', 'Pasar tradisional pagi hari', 'Restoran mewah', 'Toko online'],
    correctAnswerIndex: 1,
    explanation: 'Jajanan pasar biasanya dijual di pasar tradisional pada pagi hari.',
  },
  {
    id: 'q15',
    question: 'Isian risoles yang paling umum di Indonesia adalah?',
    options: ['Ragout ayam sayur', 'Cokelat', 'Nasi goreng', 'Mie goreng'],
    correctAnswerIndex: 0,
    explanation: 'Risoles biasanya diisi ragout yang terbuat dari ayam dan sayuran.',
  },
];
